### ISSUE TITLE
Failure in yarn tests

### ISSUE THREAD

**Issue by stianst** [edewit/keycloak-react-demo#2]
Running `mvn install` results in following error:

```
[INFO] --- frontend-maven-plugin:1.8.0:yarn (yarn test) @ react-client ---
[INFO] Running 'yarn test' in /home/st/kc/keycloak-react-demo/react-client/target/frontend
[INFO] yarn run v1.13.0
[INFO] $ CI=true react-scripts test
[INFO] PASS src/App.test.js
[INFO] (node:20386) UnhandledPromiseRejectionWarning: TypeError: Caught error after test environment was torn down
[INFO] 
[INFO] Cannot read property 'body' of null
[INFO] (node:20386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[INFO] (node:20386) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[INFO] FAIL src/__tests__/ListLoader.spec.tsx (8.946s)
[INFO]   ● Console
[INFO] 
[INFO]     console.error node_modules/@testing-library/react/dist/act-compat.js:52
[INFO]       Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
[INFO]           in DataLoader (at ListLoader.tsx:42)
[INFO] 
[INFO]   ● <FruitLoader /> › should return corresponding list of fruit
[INFO] 
[INFO]     Unable to find an element with the text: Fruit has been loaded 1. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
[INFO] 
[INFO]     <body>
[INFO]       <div>
[INFO]         <div
[INFO]           aria-label="Danger Alert"
[INFO]           class="pf-c-alert pf-m-danger"
[INFO]         >
[INFO]           <div
[INFO]             class="pf-c-alert__icon"
[INFO]           >
[INFO]             <svg
[INFO]               aria-hidden="true"
[INFO]               fill="currentColor"
[INFO]               height="1em"
[INFO]               role="img"
[INFO]               style="vertical-align: -0.125em;"
[INFO]               viewBox="0 0 512 512"
[INFO]               width="1em"
[INFO]             >
[INFO]               <path
[INFO]                 d="M504 256c0 136.997-111.043 248-248 248S8 392.997 8 256C8 119.083 119.043 8 256 8s248 111.083 248 248zm-248 50c-25.405 0-46 20.595-46 46s20.595 46 46 46 46-20.595 46-46-20.595-46-46-46zm-43.673-165.346l7.418 136c.347 6.364 5.609 11.346 11.982 11.346h48.546c6.373 0 11.635-4.982 11.982-11.346l7.418-136c.375-6.874-5.098-12.654-11.982-12.654h-63.383c-6.884 0-12.356 5.78-11.981 12.654z"
[INFO]                 transform=""
[INFO]               />
[INFO]             </svg>
[INFO]           </div>
[INFO]           <h4
[INFO]             class="pf-c-alert__title"
[INFO]           >
[INFO]             <span
[INFO]               class="pf-u-screen-reader"
[INFO]             >
[INFO]               Danger alert:
[INFO]             </span>
[INFO]             User not in role? undefined
[INFO]           </h4>
[INFO]           
[INFO]         </div>
[INFO]       </div>
[INFO]     </body>
[INFO] 
[INFO]       at getElementError (node_modules/@testing-library/dom/dist/query-helpers.js:22:10)
[INFO]       at args (node_modules/@testing-library/dom/dist/query-helpers.js:76:13)
[INFO]       at args (node_modules/@testing-library/dom/dist/query-helpers.js:59:17)
[INFO]       at node_modules/@testing-library/dom/dist/query-helpers.js:86:105
[INFO]       at MutationObserver.onMutation [as _listener] (node_modules/@testing-library/dom/dist/wait-for-element.js:46:24)
[INFO]       at check (node_modules/@sheerun/mutationobserver-shim/MutationObserver.js:47:26)
[INFO] 
[INFO] Test Suites: 1 failed, 1 passed, 2 total
[INFO] Tests:       1 failed, 1 passed, 2 total
[INFO] Snapshots:   0 total
[INFO] Time:        10.166s
[INFO] Ran all test suites.
[INFO] error Command failed with exit code 1.
[INFO] error Command failed with exit code 1.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] rest-app 1.0-SNAPSHOT .............................. SUCCESS [  1.092 s]
[INFO] react-client ....................................... FAILURE [01:30 min]
[INFO] rest-json 1.0-SNAPSHOT ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:32 min
[INFO] Finished at: 2019-12-12T09:48:37+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:yarn (yarn test) on project react-client: Failed to run task: 'yarn test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to ena
```

**Comment by edewit** [comment]
fixed with 837d316
